import { ServicePageTemplate } from "@/components/service-page-template"

const visiCoolersData = {
  serviceName: "Visi Cooler Services",
  serviceDescription:
    "Professional visi cooler repair and maintenance services for retail and commercial use. Expert solutions for display coolers with transparent doors and optimal product visibility.",
  heroImage: "/visi-cooler-repair.png",
  categories: [
    {
      title: "Visi Cooler Repairs & Servicing",
      services: [
        {
          id: "complete-servicing",
          name: "Complete Servicing",
          description: "Comprehensive visi cooler maintenance and performance optimization",
          image: "/visi-cooler-repair.png",
          issues: [
            "Regular maintenance needed",
            "Performance optimization",
            "Energy efficiency check",
            "Display visibility enhancement",
            "Overall system health",
          ],
        },
        {
          id: "demo",
          name: "Demo",
          description: "Professional setup and demonstration of new visi coolers",
          image: "/visi-cooler-repair.png",
          issues: [
            "New appliance installation",
            "Temperature settings",
            "Display optimization",
            "Feature explanation",
            "Usage guidelines",
          ],
        },
        {
          id: "electrical-problem",
          name: "Electrical Problem",
          description: "General electrical issues and power-related problems",
          image: "/visi-cooler-repair.png",
          issues: [
            "Cooler not starting",
            "Power supply issues",
            "Electrical short circuits",
            "Control panel problems",
            "Wiring malfunction",
          ],
        },
        {
          id: "relay-problem",
          name: "Relay Problem",
          description: "Relay repair and replacement for proper electrical control",
          image: "/visi-cooler-repair.png",
          issues: [
            "Relay malfunction",
            "Intermittent operation",
            "Starting problems",
            "Electrical control issues",
            "Component failure",
          ],
        },
        {
          id: "capacitors-problem",
          name: "Capacitors Problem",
          description: "Capacitor diagnosis and replacement services",
          image: "/visi-cooler-repair.png",
          issues: [
            "Capacitor failure",
            "Starting difficulties",
            "Motor problems",
            "Electrical efficiency issues",
            "Component burnout",
          ],
        },
        {
          id: "thermostat-problem",
          name: "Thermostat Problem",
          description: "Temperature control and thermostat repair",
          image: "/visi-cooler-repair.png",
          issues: [
            "Temperature control issues",
            "Thermostat malfunction",
            "Inaccurate readings",
            "Auto-cycling problems",
            "Temperature fluctuation",
          ],
        },
        {
          id: "gas-problem",
          name: "Gas Problem",
          description: "Refrigerant system repair and gas refilling",
          image: "/visi-cooler-repair.png",
          issues: [
            "Insufficient cooling",
            "Gas leakage",
            "Pressure imbalance",
            "Temperature inconsistency",
            "High energy consumption",
          ],
        },
        {
          id: "compressor-problem",
          name: "Compressor Problem",
          description: "Professional compressor repair and replacement",
          image: "/visi-cooler-repair.png",
          issues: [
            "Compressor failure",
            "Strange noises",
            "Overheating",
            "Frequent cycling",
            "Poor cooling performance",
          ],
        },
        {
          id: "condenser-fan-motor",
          name: "Condenser Fan Motor",
          description: "Fan motor repair for optimal heat dissipation",
          image: "/visi-cooler-repair.png",
          issues: ["Fan not working", "Noisy operation", "Motor overheating", "Poor ventilation", "Reduced efficiency"],
        },
        {
          id: "body-repair",
          name: "Body Repair",
          description: "Physical damage repair and body restoration",
          image: "/visi-cooler-repair.png",
          issues: [
            "Dents and scratches",
            "Door alignment issues",
            "Handle problems",
            "Rust treatment",
            "Physical wear repair",
          ],
        },
        {
          id: "accessories",
          name: "Accessories",
          description: "Replacement of shelves, lighting, and internal components",
          image: "/visi-cooler-repair.png",
          issues: ["Broken shelves", "Lighting issues", "Door seals", "Internal components", "Display accessories"],
        },
        {
          id: "condenser-fan-blade",
          name: "Condenser Fan Blade Problem",
          description: "Fan blade repair and replacement services",
          image: "/visi-cooler-repair.png",
          issues: ["Broken fan blades", "Bent blades", "Imbalanced rotation", "Noise issues", "Reduced airflow"],
        },
        {
          id: "electronic-thermometer",
          name: "Electronic Thermometer",
          description: "Digital temperature display repair and calibration",
          image: "/visi-cooler-repair.png",
          issues: [
            "Inaccurate readings",
            "Display malfunction",
            "Sensor problems",
            "Calibration needed",
            "Electronic failure",
          ],
        },
        {
          id: "fan-motor-base",
          name: "Fan Motor Base Problem",
          description: "Motor mounting and base stabilization",
          image: "/visi-cooler-repair.png",
          issues: ["Loose motor mounting", "Vibration problems", "Base damage", "Alignment issues", "Motor base noise"],
        },
        {
          id: "door-closing",
          name: "Door Closing Problem",
          description: "Door mechanism and seal repair for proper closure",
          image: "/visi-cooler-repair.png",
          issues: ["Door not closing", "Loose seals", "Hinge problems", "Latch issues", "Air leakage"],
        },
        {
          id: "water-leakage",
          name: "Water Leakage Problem",
          description: "Water leak detection and drainage system repair",
          image: "/visi-cooler-repair.png",
          issues: ["Water accumulation", "Drain blockage", "Condensation issues", "Pipe leakage", "Defrost problems"],
        },
        {
          id: "electrical-wire",
          name: "Electrical Wire Problem",
          description: "Wiring inspection and electrical safety repairs",
          image: "/visi-cooler-repair.png",
          issues: ["Loose connections", "Damaged wiring", "Short circuit risks", "Power issues", "Safety concerns"],
        },
        {
          id: "tube-light",
          name: "Tube Light Problem",
          description: "Internal lighting repair and replacement",
          image: "/visi-cooler-repair.png",
          issues: [
            "Tube light not working",
            "Flickering lights",
            "Ballast problems",
            "LED conversion",
            "Poor product visibility",
          ],
        },
        {
          id: "door-beeding",
          name: "Door Beeding Problem",
          description: "Door edge sealing and beading repair",
          image: "/visi-cooler-repair.png",
          issues: [
            "Damaged door beeding",
            "Air leakage",
            "Seal deterioration",
            "Energy loss",
            "Temperature inconsistency",
          ],
        },
        {
          id: "front-glass",
          name: "Front Glass Problem",
          description: "Glass door repair and replacement services",
          image: "/visi-cooler-repair.png",
          issues: [
            "Cracked glass",
            "Fogging issues",
            "Glass replacement needed",
            "Visibility problems",
            "Insulation issues",
          ],
        },
      ],
    },
  ],
  testimonials: [
    {
      name: "Deepak Gupta",
      rating: 5,
      comment: "Excellent service for our store's visi cooler. Professional glass replacement.",
      service: "Front Glass Problem",
    },
    {
      name: "Anita Sharma",
      rating: 5,
      comment: "Quick repair of the cooling system. Very satisfied with the service.",
      service: "Gas Problem",
    },
    {
      name: "Vijay Kumar",
      rating: 5,
      comment: "Professional lighting repair. Products are now clearly visible to customers.",
      service: "Tube Light Problem",
    },
  ],
}

export default function VisiCoolersPage() {
  return <ServicePageTemplate {...visiCoolersData} />
}
