import { ServicePageTemplate } from "@/components/service-page-template"

const waterCoolersData = {
  serviceName: "Water Cooler Services",
  serviceDescription:
    "Professional water cooler repair and maintenance services for offices and commercial spaces. Expert solutions for all water cooler brands with same-day service availability.",
  heroImage: "/water-cooler-repair.png",
  categories: [
    {
      title: "Water Cooler Repairs & Servicing",
      services: [
        {
          id: "complete-servicing",
          name: "Complete Servicing",
          description: "Comprehensive water cooler maintenance and sanitization",
          image: "/water-cooler-repair.png",
          issues: [
            "Regular maintenance needed",
            "Water quality optimization",
            "Sanitization required",
            "Performance check",
            "Preventive care",
          ],
        },
        {
          id: "demo",
          name: "Demo",
          description: "Professional setup and demonstration of new water coolers",
          image: "/water-cooler-repair.png",
          issues: [
            "New appliance installation",
            "Water connection setup",
            "Temperature settings",
            "Feature explanation",
            "Usage guidelines",
          ],
        },
        {
          id: "electrical-problem",
          name: "Electrical Problem",
          description: "Electrical system repair and troubleshooting",
          image: "/water-cooler-repair.png",
          issues: [
            "Cooler not starting",
            "Power supply issues",
            "Electrical connections",
            "Control panel problems",
            "Wiring malfunction",
          ],
        },
        {
          id: "relay-problem",
          name: "Relay Problem",
          description: "Relay repair and replacement for proper operation",
          image: "/water-cooler-repair.png",
          issues: [
            "Relay malfunction",
            "Starting problems",
            "Intermittent operation",
            "Control issues",
            "Component failure",
          ],
        },
        {
          id: "capacitors-problem",
          name: "Capacitors Problem",
          description: "Capacitor diagnosis and replacement services",
          image: "/water-cooler-repair.png",
          issues: [
            "Capacitor failure",
            "Starting difficulties",
            "Motor problems",
            "Electrical efficiency loss",
            "Component burnout",
          ],
        },
        {
          id: "thermostat-problem",
          name: "Thermostat Problem",
          description: "Temperature control and thermostat repair",
          image: "/water-cooler-repair.png",
          issues: [
            "Temperature control issues",
            "Thermostat malfunction",
            "Inaccurate readings",
            "Auto-cycling problems",
            "Water temperature fluctuation",
          ],
        },
        {
          id: "gas-problem",
          name: "Gas Problem",
          description: "Refrigerant system repair and gas refilling",
          image: "/water-cooler-repair.png",
          issues: [
            "Insufficient cooling",
            "Gas leakage",
            "Pressure problems",
            "Temperature inconsistency",
            "High energy consumption",
          ],
        },
        {
          id: "compressor-problem",
          name: "Compressor Problem",
          description: "Professional compressor repair and replacement",
          image: "/water-cooler-repair.png",
          issues: [
            "Compressor failure",
            "Strange noises",
            "Overheating issues",
            "Frequent cycling",
            "Poor cooling performance",
          ],
        },
        {
          id: "condenser-fan-motor",
          name: "Condenser Fan Motor",
          description: "Fan motor repair for optimal heat dissipation",
          image: "/water-cooler-repair.png",
          issues: ["Fan not working", "Noisy operation", "Motor overheating", "Poor ventilation", "Reduced efficiency"],
        },
        {
          id: "body-repair",
          name: "Body Repair",
          description: "Physical damage repair and body restoration",
          image: "/water-cooler-repair.png",
          issues: [
            "Dents and scratches",
            "Tap mounting issues",
            "Handle problems",
            "Rust treatment",
            "Physical damage",
          ],
        },
        {
          id: "accessories",
          name: "Accessories",
          description: "Water cooler accessories and component replacement",
          image: "/water-cooler-repair.png",
          issues: ["Broken accessories", "Water filters", "Drip trays", "Internal components", "Replacement parts"],
        },
        {
          id: "condenser-fan-blade",
          name: "Condenser Fan Blade Problem",
          description: "Fan blade repair and replacement services",
          image: "/water-cooler-repair.png",
          issues: ["Broken fan blades", "Bent blades", "Imbalanced rotation", "Noise issues", "Reduced airflow"],
        },
        {
          id: "electronic-thermometer",
          name: "Electronic Thermometer",
          description: "Temperature monitoring system repair and calibration",
          image: "/water-cooler-repair.png",
          issues: [
            "Inaccurate readings",
            "Display malfunction",
            "Sensor problems",
            "Calibration needed",
            "Electronic failure",
          ],
        },
        {
          id: "fan-motor-base",
          name: "Fan Motor Base Problem",
          description: "Motor mounting and base stabilization",
          image: "/water-cooler-repair.png",
          issues: ["Loose motor mounting", "Vibration problems", "Base damage", "Alignment issues", "Motor base noise"],
        },
        {
          id: "door-closing",
          name: "Door Closing Problem",
          description: "Door mechanism and seal repair for storage compartments",
          image: "/water-cooler-repair.png",
          issues: ["Door not closing", "Loose seals", "Hinge problems", "Latch issues", "Storage access problems"],
        },
        {
          id: "water-leakage",
          name: "Water Leakage Problem",
          description: "Water leak detection and plumbing repair",
          image: "/water-cooler-repair.png",
          issues: ["Water leakage", "Pipe connections", "Internal leaks", "Drip tray overflow", "Plumbing issues"],
        },
        {
          id: "electrical-wire",
          name: "Electrical Wire Problem",
          description: "Wiring inspection and electrical safety repairs",
          image: "/water-cooler-repair.png",
          issues: ["Loose connections", "Damaged wiring", "Short circuit risks", "Power issues", "Safety concerns"],
        },
        {
          id: "tap-problem",
          name: "Tap Problem",
          description: "Water tap repair and replacement services",
          image: "/water-cooler-repair.png",
          issues: [
            "Tap not working",
            "Leaking taps",
            "Poor water flow",
            "Tap mechanism issues",
            "Water dispensing problems",
          ],
        },
        {
          id: "door-beeding",
          name: "Door Beeding Problem",
          description: "Door sealing and beading repair for storage areas",
          image: "/water-cooler-repair.png",
          issues: [
            "Damaged door beeding",
            "Air leakage",
            "Seal deterioration",
            "Energy loss",
            "Temperature inconsistency",
          ],
        },
      ],
    },
  ],
  testimonials: [
    {
      name: "Pradeep Singh",
      rating: 5,
      comment: "Excellent water cooler service for our office. Clean and professional work.",
      service: "Water Cooler Repair",
    },
    {
      name: "Sunita Devi",
      rating: 5,
      comment: "Quick tap repair service. Water flow is perfect now. Highly recommended!",
      service: "Tap Problem",
    },
    {
      name: "Manoj Kumar",
      rating: 5,
      comment: "Professional cooling system repair. Very satisfied with the service quality.",
      service: "Gas Problem",
    },
  ],
}

export default function WaterCoolersPage() {
  return <ServicePageTemplate {...waterCoolersData} />
}
